### ISSUE TITLE
Auto-loading `config/schedule.yml` feature causes an error with Array style schedule.yml definition.

### ISSUE THREAD

**Issue by machisuke** [ondrejbartas/sidekiq-cron#346]
The auto-loading introduced in https://github.com/ondrejbartas/sidekiq-cron/pull/337 supports Hash format schedule, but not Array format.

For example, with the bellow `config/schedule.yml`,
```yml
-
  name: 'my_first_job'
  class: 'MyFirstJob'
  cron: '1 * * * *'
  description: |
    my_first_job
-
  name: 'my_second_job'
  class: 'MySecondJob'
  cron: '2 * * * *'
  description: |
    my_second_job
```

the auto-loading causes the below error.

```ruby
2022-07-11T08:58:27.831Z pid=22 tid=7ge WARN: NoMethodError: undefined method `[]=' for nil:NilClass
2022-07-11T08:58:27.831Z pid=22 tid=7ge WARN: /usr/local/bundle/gems/sidekiq-cron-1.6.0/lib/sidekiq/cron/job.rb:152:in `block in load_from_hash'
/usr/local/bundle/gems/sidekiq-cron-1.6.0/lib/sidekiq/cron/job.rb:151:in `each'
/usr/local/bundle/gems/sidekiq-cron-1.6.0/lib/sidekiq/cron/job.rb:151:in `inject'
/usr/local/bundle/gems/sidekiq-cron-1.6.0/lib/sidekiq/cron/job.rb:151:in `load_from_hash'
/usr/local/bundle/gems/sidekiq-cron-1.6.0/lib/sidekiq/cron/schedule_loader.rb:11:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:56:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:55:in `each'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:55:in `fire_event'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/cli.rb:105:in `run'
/usr/local/bundle/gems/sidekiq-6.5.1/bin/sidekiq:31:in `<top (required)>'
bin/sidekiq:29:in `load'
bin/sidekiq:29:in `<main>'
```
